### ISSUE TITLE
Question about iterative LSI parameters used for constructing the normal epithelial reference

### ISSUE THREAD

**Issue by RegnerM2015** [winstonbecker/scCRC_continuum#1]
Hi @winstonbecker and @snevins1,

Great work and congratulations on the publication! 

I noticed that non-default LSI parameters were used for constructing the normal epithelial reference:

```
proj <- addIterativeLSI(
    ArchRProj = proj,
    useMatrix = "TileMatrix", 
    name = paste("IterativeLSI", subscript, sep = ""), 
    iterations = 4, 
    clusterParams = list(
        resolution = c(0.1, 0.1, 0.2), 
        sampleCells = 10000, 
        n.start = 10
    ), 
    varFeatures = 15000, sampleCellsPre = NULL,
    dimsToUse = 1:25, force = TRUE
)
```

Would you be able to provide some insights into why you chose 15k variable features instead of 25k variable features? Additionally, I am interested in learning why the number of iterations was increased from 2 to 4. 

Thanks for your help! I hope to implement these insights into my own work.

**Comment by winstonbecker** [comment]
Hi @RegnerM2015 , 

Thanks for you interest in the paper!

For selecting the number of variable features we found that using the top 15K features captured most of the biological variation, while increasing the number of features to 25K led to some of the samples starting to cluster more by donor/sample, suggesting that the additional features captured donor specific differences that we were less interested in capturing. 

Similarly, for the number of iterations, 4 was selected because it also helped us remove subtle batch effects between different samples.

**Comment by RegnerM2015** [comment]
Thank you for answering my questions! I really appreciate the help.
